load("//build-support/buck:workspace_rules.bzl", "workspace_binary")

workspace_binary(
    name = "replayshark_bin",
    crate = "replayshark",
    package = "replayshark",
    version = "0.1.0",
    crate_root = "src/main.rs",
    deps = [
        "//crates/wows-battle-world:wows_battle_world",
        "//crates/wows-data-mgr:wows_data_mgr",
        "//crates/wows-replay-insights:wows_replay_insights",
        "//crates/wows-replays:wows_replays",
        "//crates/wowsunpack:wowsunpack",
        "//third-party/rust:clap",
        "//third-party/rust:gettext",
        "//third-party/rust:jiff",
        "//third-party/rust:parse_int",
        "//third-party/rust:rootcause",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
        "//third-party/rust:toml",
        "//third-party/rust:walkdir",
    ],
)
