load(":hermetic_rust.bzl", "hermetic_cxx_toolchain", "hermetic_python_bootstrap_toolchain", "hermetic_rust_toolchain", "validate_nix_toolchain")

validate_nix_toolchain()

hermetic_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

hermetic_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

hermetic_rust_toolchain(
    name = "rust",
    default_edition = "2024",
    rustc_target_triple = "aarch64-apple-darwin",
    visibility = ["PUBLIC"],
)
