load("//build-support/buck:workspace_rules.bzl", "workspace_library")

workspace_library(
    name = "wt_translations",
    crate = "wt_translations",
    package = "wt-translations",
    version = "0.16.0",
    deps = ["//crates/wows-core:wows_core"],
)
