export_file(
    name = "wows_toolkit_png",
    src = "wows_toolkit.png",
    visibility = ["PUBLIC"],
)

export_file(
    name = "wows_toolkit_ico",
    src = "wows_toolkit.ico",
    visibility = ["PUBLIC"],
)

export_file(
    name = "wows_toolkit_rc",
    src = "wows_toolkit.rc",
    visibility = ["PUBLIC"],
)
