load(":hermetic_msvc.bzl", "hermetic_msvc_rust_toolchain", "hermetic_msvc_tools", "windows_resource")
load(":windows-x86_64-msvc.bzl", "windows_x86_64_msvc_platform")
load(":wix.bzl", "wix_msi")
load("@prelude//toolchains:cxx.bzl", "cxx_tools_info_toolchain")

hermetic_msvc_tools(
    name = "msvc_tools",
    visibility = ["PUBLIC"],
)

cxx_tools_info_toolchain(
    name = "cxx",
    cxx_tools_info = ":msvc_tools",
    c_flags = ["/nologo", "/Brepro"],
    cxx_flags = ["/nologo", "/Brepro"],
    link_flags = ["/Brepro", "/INCREMENTAL:NO"],
    visibility = ["PUBLIC"],
)

hermetic_msvc_rust_toolchain(
    name = "rust",
    default_edition = "2024",
    tools = ":msvc_tools",
    visibility = ["PUBLIC"],
)

windows_x86_64_msvc_platform(
    name = "windows_x86_64_msvc",
    visibility = ["PUBLIC"],
)

windows_resource(
    name = "app_resource",
    src = "root//assets:wows_toolkit_rc",
    resources = ["root//assets:wows_toolkit_ico"],
    tools = ":msvc_tools",
    out = "wows_toolkit.res",
    visibility = ["PUBLIC"],
)

wix_msi(
    name = "wows_toolkit_msi",
    tools = ":msvc_tools",
    wxs = ["root//wix:main_wxs"],
    assets = [
        "root//assets:wows_toolkit_ico",
        "root//wix:banner_bmp",
        "root//wix:license_rtf",
    ],
    binaries = {"wows_toolkit.exe": "root//crates/wows-toolkit:wows_toolkit_bin"},
    pdbs = {},
    version_input = "root//wix:version_wxi",
    out = "wows-toolkit-windows-x86_64-unsigned.msi",
    visibility = ["PUBLIC"],
)
